In [1]:
import numpy as np

In [2]:
a = np.zeros((1, 3))

In [4]:
a.shape

(1, 3)

In [6]:
b = np.ones((3, 1))

In [7]:
b

array([[1.],
       [1.],
       [1.]])

In [8]:
c = np.array([1, 0, -1])
print(c)

[ 1  0 -1]


In [9]:
c = np.array([[1, 0, -1], [2, 0, -2]])
print(c)

[[ 1  0 -1]
 [ 2  0 -2]]


In [10]:
c.shape

(2, 3)

In [11]:
c[0, 0]

1

In [12]:
c[1, 2]

-2

In [14]:
c[1, :]

array([ 2,  0, -2])

In [15]:
c[:, 0]

array([1, 2])

In [16]:
c.shape

(2, 3)

In [17]:
d = c.reshape((3, 2))

In [18]:
d

array([[ 1,  0],
       [-1,  2],
       [ 0, -2]])

In [20]:
e = np.ones((2, 2))
np.matmul(d, e)

array([[ 1.,  1.],
       [ 1.,  1.],
       [-2., -2.]])

In [21]:
d

array([[ 1,  0],
       [-1,  2],
       [ 0, -2]])

In [22]:
d[:, [1, 0]]

array([[ 0,  1],
       [ 2, -1],
       [-2,  0]])